# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approxG <- function(y_, Z_, u_, a1_, P1_, P1inf_, dist, tol, maxiter, maxiter2, convtol, theta_, Zind_, nfactors, trace) {
    .Call('GLMMF_approxG', PACKAGE = 'GLMMF', y_, Z_, u_, a1_, P1_, P1inf_, dist, tol, maxiter, maxiter2, convtol, theta_, Zind_, nfactors, trace)
}

likelihood <- function(y_, Z_, u_, a1_, P1_, P1inf_, dist, tol, maxiter, maxiter2, convtol, theta_, Zind_, nfactors, trace, compgrad) {
    .Call('GLMMF_likelihood', PACKAGE = 'GLMMF', y_, Z_, u_, a1_, P1_, P1inf_, dist, tol, maxiter, maxiter2, convtol, theta_, Zind_, nfactors, trace, compgrad)
}

smoother <- function(y_, Z_, u_, a1_, P1_, P1inf_, dist, tol, maxiter, maxiter2, convtol, theta_, Zind_, nfactors, trace) {
    .Call('GLMMF_smoother', PACKAGE = 'GLMMF', y_, Z_, u_, a1_, P1_, P1inf_, dist, tol, maxiter, maxiter2, convtol, theta_, Zind_, nfactors, trace)
}

